#!/usr/bin/env python3
"""Classify answered-clarification dialogues using categories in clarification.md.

The input is a JSON report generated by ``clarification_eval.py``. A dialogue
is eligible only when it already has at least one ``clarification_pairs`` item,
but the model receives the complete dialogue turns for context. The output has
exactly two top-level parts: category distribution and per-dialogue judgements.
"""

from __future__ import annotations

import argparse
import copy
import json
import os
import re
import sys
import time
from pathlib import Path
from typing import Any, Mapping, Sequence
from urllib import error as urlerror
from urllib import request as urlrequest

from workspace.UserSimulatorEval.explore.clarification_eval import _content_to_text, extract_json_object, resolve_endpoint


CLASSIFICATION_SYSTEM_PROMPT = """你是客服对话分析专家。请根据输入提供的 classification_categories，对完整客服对话中的用户行为进行多标签分类。

规则：
1. 每个对话必须归入至少一个给定类别；可归入多个类别。同一类别一个对话只能归一次。不要创造、改名或合并类别。即使分类边界不完全清晰，也要选择最贴近原文行为的一个或多个已有类别。
2. 必须严格依据分类定义和原文。不回答客服的追问，必须是客服提出了一个问题，而用户的回答明显不是对这个问题的回答，才算是“未回答”，只要是回答了，就算回答的简单也算回答。使用短语的判定，不考虑二元追问的回答，比如“是的”，“对”，“没有”。主动提供背景信息，必须是客服没有问到，而用户主动提供的，且用户描述问题现象的不能算做背景信息。
3. 每个分类必须说明理由。
只能输出一个合法 JSON 对象，不要 Markdown、代码围栏或其他说明。结构必须为：
{
  "overall_reason": "对整段对话的简短判断说明",
  "category_assignments": [
    {
      "category_id": "category_1",
      "reason": "该类别适用的具体理由"
    }
  ]
}"""


class JudgeRequestError(RuntimeError):
    """HTTP/parse failure with enough detail to store in a dialogue result."""

    def __init__(self, message: str, attempts: list[dict[str, Any]]):
        super().__init__(message)
        self.attempts = attempts


class ClassificationJudge:
    """Minimal OpenAI-compatible JSON judge client."""

    def __init__(
        self,
        url: str,
        model_name: str,
        api_key: str = "",
        timeout: float = 120.0,
        max_retries: int = 2,
        temperature: float = 0.0,
        max_tokens: int = 4096,
    ):
        self.endpoint = resolve_endpoint(url)
        self.model_name = model_name
        self.api_key = api_key
        self.timeout = timeout
        self.max_retries = max(0, max_retries)
        self.temperature = temperature
        self.max_tokens = max_tokens

    def classify(self, user_prompt: str) -> dict[str, Any]:
        messages = [
            {"role": "system", "content": CLASSIFICATION_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ]
        base_payload = {
            "model": self.model_name,
            "messages": messages,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
            # Direct HTTP equivalent of the SDK's extra_body argument.
            "chat_template_kwargs": {"enable_thinking": False},
        }
        modes = [
            ("json_object", dict(base_payload, response_format={"type": "json_object"})),
            ("plain", base_payload),
        ]
        attempts: list[dict[str, Any]] = []
        last_error: Exception | None = None
        for mode, payload in modes:
            for retry_index in range(self.max_retries + 1):
                attempt = {
                    "mode": mode,
                    "retry_index": retry_index,
                    "request_body": copy.deepcopy(payload),
                }
                raw_response: str | None = None
                try:
                    raw_response = self._post_for_content(payload)
                    parsed = extract_json_object(raw_response)
                    attempt["status"] = "response_received"
                    attempt["raw_response"] = raw_response
                    attempts.append(attempt)
                    return {
                        "messages": messages,
                        "request_attempts": attempts,
                        "raw_response": raw_response,
                        "parsed_response": parsed,
                    }
                except Exception as exc:  # noqa: BLE001 - retry/fallback is intentional
                    last_error = exc
                    attempt["status"] = "failed"
                    attempt["error_type"] = type(exc).__name__
                    attempt["error"] = str(exc)
                    if raw_response is not None:
                        attempt["raw_response"] = raw_response
                    attempts.append(attempt)
                    if retry_index < self.max_retries:
                        time.sleep(min(2.0, 0.5 * (2**retry_index)))
        raise JudgeRequestError(f"LLM Judge request failed: {last_error}", attempts) from last_error

    def _post_for_content(self, payload: Mapping[str, Any]) -> str:
        data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        headers = {"Content-Type": "application/json", "Accept": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
        req = urlrequest.Request(self.endpoint, data=data, headers=headers, method="POST")
        try:
            with urlrequest.urlopen(req, timeout=self.timeout) as response:
                raw = response.read().decode("utf-8")
        except urlerror.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"HTTP {exc.code} from {self.endpoint}: {detail[:1000]}") from exc
        except urlerror.URLError as exc:
            raise RuntimeError(f"cannot reach {self.endpoint}: {exc.reason}") from exc
        try:
            response = json.loads(raw)
            content = response["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError, json.JSONDecodeError) as exc:
            raise RuntimeError(f"unexpected LLM response: {raw[:1000]}") from exc
        return _content_to_text(content)


def as_text(value: Any, maximum: int = 4000) -> str:
    return str(value).strip()[:maximum] if value is not None else ""


def as_int(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, str) and value.strip().lstrip("-").isdigit():
        return int(value.strip())
    return None


def load_json_object(path: str | Path) -> dict[str, Any]:
    source = Path(path)
    try:
        value = json.loads(source.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{source}: invalid JSON: {exc}") from exc
    if not isinstance(value, Mapping):
        raise ValueError(f"{source}: expected a top-level JSON object")
    return dict(value)


def load_categories(path: str | Path) -> list[dict[str, Any]]:
    """Read numbered classification definitions, preserving their markdown text."""

    source = Path(path)
    categories: list[dict[str, Any]] = []
    used_numbers: set[int] = set()
    for line_number, line in enumerate(source.read_text(encoding="utf-8").splitlines(), 1):
        match = re.match(r"^\s*(\d+)\s*[.、)]\s*(\S.*)$", line)
        if not match:
            continue
        number = int(match.group(1))
        definition = match.group(2).strip()
        if number in used_numbers:
            raise ValueError(f"{source}:{line_number}: duplicate category number {number}")
        used_numbers.add(number)
        categories.append(
            {
                "category_id": f"category_{number}",
                "category": definition,
            }
        )
    if not categories:
        raise ValueError(f"{source}: no numbered categories found; expected lines such as '1. 类别定义'")
    return categories


def eligible_dialogues(report: Mapping[str, Any]) -> list[dict[str, Any]]:
    dialogues = report.get("dialogues", [])
    if not isinstance(dialogues, list):
        raise ValueError("input report field 'dialogues' must be a list")
    selected: list[dict[str, Any]] = []
    for source_position, dialogue in enumerate(dialogues):
        if not isinstance(dialogue, Mapping):
            continue
        pairs = dialogue.get("clarification_pairs", [])
        turns = dialogue.get("turns", [])
        if isinstance(pairs, list) and pairs and isinstance(turns, list) and turns:
            selected.append(
                {
                    "source_position": source_position,
                    "record_index": dialogue.get("record_index", source_position),
                    "call_sno": dialogue.get("call_sno"),
                    "turns": turns,
                }
            )
    return selected


def build_user_prompt(dialogue: Mapping[str, Any], categories: Sequence[Mapping[str, Any]]) -> str:
    return (
        "请根据给定类别对 full_dialogue 分类。\n\n"
        + json.dumps(
            {
                "classification_categories": categories,
                "full_dialogue": dialogue.get("turns", []),
            },
            ensure_ascii=False,
            indent=2,
        )
    )


def normalise_judgement(raw: Mapping[str, Any], categories: Sequence[Mapping[str, Any]]) -> tuple[dict[str, Any], list[str]]:
    """Accept only known categories with non-empty reasons."""

    known_categories = {as_text(item.get("category_id")): as_text(item.get("category")) for item in categories}
    warnings: list[str] = []
    assignments: list[dict[str, Any]] = []
    seen_categories: set[str] = set()
    raw_assignments = raw.get("category_assignments", [])
    if not isinstance(raw_assignments, list):
        warnings.append("category_assignments is not a list")
        raw_assignments = []
    for position, assignment in enumerate(raw_assignments):
        if not isinstance(assignment, Mapping):
            warnings.append(f"category_assignments[{position}] is not an object")
            continue
        category_id = as_text(assignment.get("category_id"))
        if category_id not in known_categories:
            warnings.append(f"unknown category_id: {category_id}")
            continue
        if category_id in seen_categories:
            continue
        reason = as_text(assignment.get("reason"), 3000)
        if not reason:
            warnings.append(f"category {category_id} has no reason and was omitted")
            continue
        seen_categories.add(category_id)
        assignments.append(
            {
                "category_id": category_id,
                "category": known_categories[category_id],
                "reason": reason,
            }
        )
    if not assignments:
        raise ValueError("LLM response did not contain at least one valid category assignment")
    return {"overall_reason": as_text(raw.get("overall_reason"), 3000), "category_assignments": assignments}, warnings


def calculate_distribution(categories: Sequence[Mapping[str, Any]], details: Sequence[Mapping[str, Any]]) -> list[dict[str, Any]]:
    """Count each category once per successfully classified dialogue."""

    counts = {as_text(category.get("category_id")): 0 for category in categories}
    classified_count = 0
    for detail in details:
        if detail.get("status") != "classified":
            continue
        classified_count += 1
        assignments = detail.get("category_assignments", [])
        assigned_ids = {
            as_text(assignment.get("category_id"))
            for assignment in assignments
            if isinstance(assignment, Mapping)
        }
        for category_id in assigned_ids:
            if category_id in counts:
                counts[category_id] += 1
    return [
        {
            "category_id": as_text(category.get("category_id")),
            "category": as_text(category.get("category")),
            "dialogue_count": counts[as_text(category.get("category_id"))],
            "dialogue_rate_among_classified": counts[as_text(category.get("category_id"))] / classified_count if classified_count else 0.0,
        }
        for category in categories
    ]


def atomic_write_output(path: Path, categories: Sequence[Mapping[str, Any]], details: list[dict[str, Any]]) -> None:
    # Keep the persisted contract intentionally to two top-level sections.
    def source_position_key(item: Mapping[str, Any]) -> int:
        position = as_int(item.get("source_position"))
        return position if position is not None else -1

    output = {
        "category_distribution": calculate_distribution(categories, details),
        "dialogue_classifications": sorted(details, key=source_position_key),
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(json.dumps(output, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def load_resume_details(path: Path) -> list[dict[str, Any]]:
    output = load_json_object(path)
    if set(output) != {"category_distribution", "dialogue_classifications"}:
        raise ValueError("--resume output must contain exactly category_distribution and dialogue_classifications")
    details = output.get("dialogue_classifications")
    if not isinstance(details, list):
        raise ValueError("--resume output dialogue_classifications must be a list")
    return [dict(item) for item in details if isinstance(item, Mapping)]


def remove_prior_detail(details: list[dict[str, Any]], source_position: int) -> None:
    details[:] = [detail for detail in details if as_int(detail.get("source_position")) != source_position]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Classify answered-clarification dialogues against numbered categories in clarification.md.")
    parser.add_argument("input", help="JSON output produced by clarification_eval.py")
    parser.add_argument("--categories", default=str(Path(__file__).with_name("clarification.md")), help="Numbered category definitions (default: clarification.md next to this script)")
    parser.add_argument("--url", default=os.getenv("LLM_JUDGE_URL"), help="OpenAI-compatible base URL or /chat/completions endpoint (env: LLM_JUDGE_URL)")
    parser.add_argument("--model-name", "--model_name", dest="model_name", default=os.getenv("LLM_JUDGE_MODEL_NAME"), help="Model name (env: LLM_JUDGE_MODEL_NAME)")
    parser.add_argument("--api-key", "--api_key", dest="api_key", default=os.getenv("LLM_JUDGE_API_KEY", ""), help="API key (env: LLM_JUDGE_API_KEY); may be empty for local endpoints")
    parser.add_argument("--output", help="Output JSON path; default: <input stem>.category_stats.json")
    parser.add_argument("--resume", action="store_true", help="Retry unfinished/failed dialogues from an existing output file")
    parser.add_argument("--overwrite", action="store_true", help="Replace an existing output file")
    parser.add_argument("--timeout", type=float, default=120.0, help="HTTP timeout in seconds (default: 120)")
    parser.add_argument("--max-retries", type=int, default=2, help="Retries per request mode (default: 2)")
    parser.add_argument("--temperature", type=float, default=0.0, help="Model temperature (default: 0)")
    parser.add_argument("--max-tokens", type=int, default=4096, help="Maximum output tokens per dialogue (default: 4096)")
    parser.add_argument("--fail-fast", action="store_true", help="Stop at the first failed dialogue instead of recording and continuing")
    parser.add_argument("--no-progress", action="store_true", help="Disable serial progress output on stderr")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not args.url:
        parser.error("--url is required (or set LLM_JUDGE_URL)")
    if not args.model_name:
        parser.error("--model-name is required (or set LLM_JUDGE_MODEL_NAME)")
    if args.timeout <= 0:
        parser.error("--timeout must be greater than 0")
    if args.max_tokens < 1:
        parser.error("--max-tokens must be at least 1")
    if args.resume and args.overwrite:
        parser.error("--resume and --overwrite cannot be used together")

    input_path = Path(args.input)
    output_path = Path(args.output) if args.output else input_path.with_name(input_path.stem + ".category_stats.json")
    try:
        source_report = load_json_object(input_path)
        categories = load_categories(args.categories)
        dialogues = eligible_dialogues(source_report)
        judge = ClassificationJudge(
            args.url,
            args.model_name,
            args.api_key,
            args.timeout,
            args.max_retries,
            args.temperature,
            args.max_tokens,
        )
        if output_path.exists() and args.resume:
            details = load_resume_details(output_path)
        elif output_path.exists() and not args.overwrite:
            raise ValueError(f"output already exists: {output_path}; use --resume or --overwrite")
        else:
            details = []
        completed_positions = {
            as_int(detail.get("source_position"))
            for detail in details
            if detail.get("status") == "classified"
        }
        pending = [dialogue for dialogue in dialogues if dialogue["source_position"] not in completed_positions]
        atomic_write_output(output_path, categories, details)
        if not args.no_progress:
            print(
                f"[clarification-category-stats] eligible={len(dialogues)} completed={len(completed_positions)} pending={len(pending)} serial=true",
                file=sys.stderr,
                flush=True,
            )
        for pending_index, dialogue in enumerate(pending, 1):
            source_position = dialogue["source_position"]
            call_sno = dialogue.get("call_sno")
            user_prompt = build_user_prompt(dialogue, categories)
            if not args.no_progress:
                print(
                    f"[clarification-category-stats] {pending_index}/{len(pending)} call_sno={call_sno} 开始分类",
                    file=sys.stderr,
                    flush=True,
                )
            try:
                trace = judge.classify(user_prompt)
                raw_judgement = trace["parsed_response"]
                if not isinstance(raw_judgement, Mapping):
                    raise ValueError("LLM response JSON must be an object")
                judgement, warnings = normalise_judgement(raw_judgement, categories)
                detail = {
                    "source_position": source_position,
                    "record_index": dialogue.get("record_index"),
                    "call_sno": call_sno,
                    "status": "classified",
                    "full_dialogue": dialogue["turns"],
                    "overall_reason": judgement["overall_reason"],
                    "category_assignments": judgement["category_assignments"],
                    "normalisation_warnings": warnings,
                }
                remove_prior_detail(details, source_position)
                details.append(detail)
                atomic_write_output(output_path, categories, details)
                if not args.no_progress:
                    print(
                        f"[clarification-category-stats] {pending_index}/{len(pending)} call_sno={call_sno} 完成，类别 {len(judgement['category_assignments'])} 个",
                        file=sys.stderr,
                        flush=True,
                    )
            except KeyboardInterrupt:
                atomic_write_output(output_path, categories, details)
                print(f"[clarification-category-stats] 已中断；结果已保存到 {output_path}", file=sys.stderr, flush=True)
                return 130
            except Exception as exc:  # noqa: BLE001 - retain failures in the second output section
                detail = {
                    "source_position": source_position,
                    "record_index": dialogue.get("record_index"),
                    "call_sno": call_sno,
                    "status": "failed",
                    "full_dialogue": dialogue["turns"],
                    "category_assignments": [],
                    "error_type": type(exc).__name__,
                    "error": str(exc),
                }
                if isinstance(exc, JudgeRequestError):
                    detail["request_attempts"] = exc.attempts
                remove_prior_detail(details, source_position)
                details.append(detail)
                atomic_write_output(output_path, categories, details)
                print(
                    f"[clarification-category-stats] {pending_index}/{len(pending)} call_sno={call_sno} 失败（{type(exc).__name__}: {exc}），已保存并继续",
                    file=sys.stderr,
                    flush=True,
                )
                if args.fail_fast:
                    return 1
        if not args.no_progress:
            classified = sum(1 for detail in details if detail.get("status") == "classified")
            failed = sum(1 for detail in details if detail.get("status") == "failed")
            print(
                f"[clarification-category-stats] 完成：成功 {classified}/{len(dialogues)}，失败 {failed}；结果：{output_path}",
                file=sys.stderr,
                flush=True,
            )
        return 0
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
